### ISSUE TITLE
How to build + install on Windows?

### ISSUE THREAD

**Issue by brandonros** [esaulenka/ghidra_v850#15]
I don't have GNU make installed on Windows. What would the sleigh.bat commands be?

**Comment by esaulenka** [comment]
You can compile sleigh in the same way, as before (see issue https://github.com/esaulenka/ghidra_v850/issues/13).
The only difference is there is second processor rules. So, you should run `sleigh.bat` twice: with `v850e2.slaspec` and with `v850e3.slaspec`

**Comment by nihalot** [comment]
hi, I compiled both and then copied data folder to $(GHIDRA_HOM)/Ghidra/Extensions but the processor module is not showing up when I load a bin file. What am I missing?

**Comment by esaulenka** [comment]
@nihalot, you should copy whole folder (starting from v850) to Extension.
You must get the following:

```
$(GHIDRA_HOME)
    Ghidra
        Extensions
             extension name, v850 for example
                 data
                       languages
                            set of v850 files
                 Module.manifest
                 extension.properties
```

Also, fork of this extension already included in latest Ghidra release. If you want to use my version, first delete Ghidra/Processors/V850

**Comment by nihalot** [comment]
I didn't get Module.manifest or extension.properties when I built this. I'm on win10 if that's relevant

Thanks for the tip, I tried the official release and I can't set "r5". It's shown as "r4r5(64)" in set register menu.
Otherwise seems fine

**Comment by esaulenka** [comment]
Module.manifest and extension.properties are in root folder in my project. Sleigh compiler only produces .sla file from .slaspec (and .sinc includes).
`r5` called `tp` (text pointer). Another shortcuts can be found [here](https://github.com/NationalSecurityAgency/ghidra/blob/133d6c251fd524ed0d0d4c962c0c02206a168975/Ghidra/Processors/V850/data/languages/Helpers/Register.sinc#L8-L14).

**Comment by brandonros** [comment]
for me for the future:

```shell
make SLEIGH=/opt/homebrew/Cellar/ghidra/12.0.4/libexec/support/sleigh JAVA_HOME=/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home
cp -r . /opt/homebrew/Cellar/ghidra/12.0.4/libexec/Ghidra/Extensions/ghidra_v850
```
