### ISSUE TITLE
Symbol duplicate for V850e3.slaspec

### ISSUE THREAD

**Issue by lixiaofan1318** [esaulenka/ghidra_v850#18]
![v850e3_error](https://user-images.githubusercontent.com/34480122/174926241-edda8cf1-cb8b-4172-976b-9b73e17b8d86.png)

Trying to compile v850e3.slaspec with "sleigh.bat" under "support" folder of Ghidra 10.1.2.  but sleigh.bat reports ERROR regarding symbol duplication.  It looks like a double-definition of SCBP and SCCFG in the file of v850e3.sinc and v850_common.sinc, which are both included in v850e3.slaspec. 

Can you please advise and help?  Thanks.

**Comment by esaulenka** [comment]
Hello. 
Looks like now SLEIGH has become case-insensitive.
Fast and dirty solution - just delete one of it. I did it, please updae.

I don't have 850e3 specification, and just did some reverse `gcc` sources for it (if you have one, please share it).
So, I am not sure, what register should be used. So, maybe you can face with issues with `stsr` / `ldsr` instructions in real firmware.
