### ISSUE TITLE
BINS operation disassebled incorretly

### ISSUE THREAD

**Issue by darkleon78** [esaulenka/ghidra_v850#28]
Hi.
Example of correct operand from real Renesas OCD:
fde7b8f0          bins            r29, 0x4, 0x1c, r28

Disassembled by IDA:
bins    r29, 4, 0x1C, r28

Disassebmled by Ghidra and your extension:
fd e7 b8 f0     bins       r29,0x4,0x1b,r28

You can see that extension show 0x1b instead of 0x1c

All BINS operand incorectly disassembled:
bins    r29, 5, 0x1B, r1 - IDA Correct

bins       r29,0x5,0x1a,r1 - incorrect by extension

Always incorrect disassembled command contains wrong bits offset (0x1B instead of 0x1C) (0x1A instead of 0x1B) and so

**Comment by esaulenka** [comment]
Could you provide more samples?

With your initial issue
example from IDA: `f3 0f dc 90 bins r19, 0x6, 0x4, r1`

my implementation returns  `f3 0f dc 90     bins       r19,0x6,0xd,r1`

This instruction has a very weird encoding, and I need more samples to test it completely.

**Comment by darkleon78** [comment]
Hi.
Ok not a problem
Here is some examples with different width and registers in BINS operand

OK:   ->   f3 0f dc 90    bins       r19, 6, 4, r1
NOK: ->  f3 0f dc 90     bins       r19,0x6,0xd,r1

OK:  ->    f3 0f b2 f0    bins       r19, 1, 0x1F, r1
NOK: ->  f3 0f b2 f0     bins       r19,0x1,0x1e,r1

OK:  ->   ef 0f d4 f0     bins    	r15, 2, 0xE, r1
NOK: ->  ef 0f d4 f0     bins       r15,0x2,0x1d,r1

OK:  ->    e1 9f b8 18   bins    	r1, 0xC, 6, r19
NOK: ->  e1 9f b8 18   bins     r1,0xc,0x8,r19

All OK tested on IDA and Renesas OCD on real chip debugging

**Comment by esaulenka** [comment]
got it!
I have picked more bits for WIDTH, so it gave a wrong result
