### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by evgenybozhko2** [esaulenka/ghidra_v850#29]
Hello, sorry for the maybe stupid question. But what is this repo exactly? Is there a processor which is already in Ghidra public release? v850/e1/e2/e2m. Or does this data have a lot of differences? If yes, do you have any instructions on using it inside Ghidra? To decompile and understand the sources of my v850e2. Thanks and sorry.

**Comment by evgenybozhko2** [comment]
I got it. Thanks. 
I'm working with v850e2. So still no very good luck with pseudo code.
Do you planing to improve v850e2 processors architects in ghidra ?

**Comment by esaulenka** [comment]
> I'm working with v850e2. So still no very good luck with pseudo code.

I need more details to understand what happens.
Probably, you loaded binary at wrong address (check datasheet for your MCU to find correct one), not added a RAM/Peripheral areas (it also specified in datasheet) or maybe your application uses GP/TP registers (you should find startup code that write value to it and set same value manually).
Also issue with a CALLT instruction is still there (same as in 'official' branch), so if your application uses it, you will have some strange code at beginning/end of all functions.

If you need more help and can share binary, try to contact me via telegram with the same nick.
