### ISSUE TITLE
First operand of cmp instruction always zero

### ISSUE THREAD

**Issue by pd0wm** [esaulenka/ghidra_v850#4]
I have a weird issue where the first operand of the `cmp` instruction is always 0. See screenshot:
![2019-11-24-013522_765x631_scrot](https://user-images.githubusercontent.com/1314752/69492777-66ef6800-0e5b-11ea-82b5-4e2a9bc6f707.png)

**Comment by pd0wm** [comment]
The problem seems to arise from the helper register (R0004 & R1115) that make sure r0 always read as zero. If I use the registers r0004 and r1115 directly it works fine.

**Comment by esaulenka** [comment]
Willem, try to reanalyze binary once more: select code, press 'C', then 'D'.
I saw this problem earlier, but now register reding fixed.

Now it works correct:
assembler code
![image](https://user-images.githubusercontent.com/12969211/69545984-e8eaa880-0fa3-11ea-81b0-77e31ced44c8.png)

decompiles to
![image](https://user-images.githubusercontent.com/12969211/69545766-78438c00-0fa3-11ea-984a-d5497a353938.png)

**Comment by shrlnm** [comment]
Hello
First of all thank you for your work. 
May I ask a question how you get such clean decompiled code as on the message above?
I get the next a bit confusing sintaksis
![Screenshot 2019-11-26 at 12 15 57](https://user-images.githubusercontent.com/16278412/69615857-a9c16380-1046-11ea-958c-ed59d53f49d8.png)
As I realise, the gp is undefined and it is reason why I get such decompiled code.
May I some hove to influence on this?

**Comment by esaulenka** [comment]
@shrlnm, as I know (but I am not sure, I didnt research any renesas compilers), compiler writes `gp` and `tp` only once in program, and then uses it for indirect addressing.
If you find place that writes to `gp` and `tp` (it should be near startup code), you can write these values: in ghidra select whole code, press right mouse button and select `set register value`.
After all, you should reanalyze program. I dont know correct way, but `select instructions` -> `clear` -> `decompile` works fine.

**Comment by shrlnm** [comment]
@esaulenka Thank you. It is works fine!
I selected all code and defined gp value as 0. Then just pressed A button for reanalysing

**Comment by pd0wm** [comment]
@esaulenka oops, you are right. Didn't realize you had to manually delete and decompile again to pull these changes from the sleigh file. Thanks!
