### ISSUE TITLE
Missing opinion file

### ISSUE THREAD

**Issue by HexRoman** [esaulenka/ghidra_v850#8]
The project doesn't contain an opinion file, that is required for the `analyzeHeadless` for loading file an ELF.

**Comment by HexRoman** [comment]
I created a PR with the file

**Comment by esaulenka** [comment]
Roman, thanks!

Please, also add same file to https://github.com/Aleckaj/ghidra
My repo slightly outdated, but Alexander tries to push similar code to main Ghidra sources.
